### PR TITLE
Infra/CI: Fix and enable build & test on Windows.

### LINKED ISSUE #69: Support build on Windows (Build issue, illegal escape)
I've tryed to run tests. I got this error. Please help.
Seems like escaping slash is missed
image

### PR DESCRIPTION
**Pull request by Jeffset**
Fix line-separators and -endings for Win in some places.

Closes #69

### CODE REVIEW

File: testing/tests/src/main/kotlin/JapCompileTestDriver.kt [hunk 1]
```diff
@@ -37,7 +37,7 @@ class JapCompileTestDriver(
 
     private fun loadProcessorFromCustomClasspath(): Processor? {
         customProcessorClasspath ?: return null
-        val kaptClassloader = URLClassLoader(customProcessorClasspath.split(":")
+        val kaptClassloader = URLClassLoader(customProcessorClasspath.split(System.getProperty("path.separator"))
```
Comment (bacecek) [inline testing/tests/src/main/kotlin/JapCompileTestDriver.kt:40]: `File.pathSeparator`?

File: settings.gradle.kts [hunk 2]
```diff
@@ -1,3 +1,7 @@
+plugins {
+    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
```
Comment (bacecek) [inline settings.gradle.kts:2]: Is that required? Seems like it's not using

Comment (Jeffset) [reply settings.gradle.kts:2]: It's not required, just a convenience for the contributors.
I used it for Windows to avoid manually installing required JDKs. Thought, that it might be useful in general, to let gradle automatically resolve and download JDKs. What do you think?

File: testing/tests/src/main/kotlin/JapCompileTestDriver.kt (hunk 1 above)
Comment (Jeffset) [reply testing/tests/src/main/kotlin/JapCompileTestDriver.kt]: Done

File: settings.gradle.kts (hunk 2 above)
Comment (bacecek) [reply settings.gradle.kts:2]: I finally got it.
Gradle documentation looks confusing and I thought that this plugin requires some configuration, but as far as I understand "convention" plugins means having some default settings.
Sorry for misunderstanding.

**Review by bacecek — APPROVED** [review]
