### PR TITLE
Don't generate AssistedFactory for unsupported variants

### LINKED ISSUE #209: Assisted factory is generated for unsupported variants
## Description:
The following code results in the generation of `PhoneAssistedFactoryImpl` inside `TabletComponent`, with an `Optional` in the constructor, which then leads to a compilation error:

```
@AssistedFactory
interface PhoneAssistedFactory {
    fun create(i: Int): PhoneAssistedClass
}

@Conditional(onlyIn = [DeviceType.Phone::class])
class PhoneAssistedClass @AssistedInject constructor(
    phoneDependency: PhoneDependency,
    @Assisted arg: Int,
)

@Conditional(onlyIn = [DeviceType.Phone::class])
class PhoneDependency @Inject constructor()

class CommonClass @Inject constructor(
    phoneFactory: Optional<PhoneAssistedFactory>,
)


interface CommonComponent {
    fun getCommonClass(): CommonClass
}

@Component(variant = [DeviceType.Phone::class])
interface PhoneComponent: CommonComponent

@Component(variant = [DeviceType.Tablet::class])
interface TabletComponent: CommonComponent
```

```
/Users/newuserkk/projects/newuserkk/yatagan-assisted-factory-reproducer/app/build/generated/source/kapt/debug/com/newuserkk/yatagan/Yatagan$TabletComponent.java:32: error: incompatible types: no instance(s) of type variable(s) T exist so that Optional<T> conforms to PhoneDependency
      return new PhoneAssistedClass(Optional.empty(), i);
             ^
  where T is a type-variable:
    T extends Object declared in method <T>empty()
```

## Expected result
An assisted factory should probably not be generated for an unsupported variant component at all

## Environment
Yatagan 1.6.1 with kapt

## Minimal reproducer
https://github.com/NewUserKK/yatagan-assisted-factory-reproducer

### PR DESCRIPTION
**Pull request by bacecek**
Fixes #209

### CODE REVIEW

File: core/graph/impl/src/main/kotlin/BindingGraphImpl.kt [hunk 1]
```diff
@@ -121,7 +121,7 @@ internal class BindingGraphImpl(
     internal val localNodes = mutableSetOf<NodeModel>()
     override val localBindings = mutableMapOf<Binding, BindingUsageImpl>()
     override val localConditionLiterals = mutableMapOf<ConditionModel, LiteralUsage>()
-    override val localAssistedInjectFactories = mutableSetOf<AssistedInjectFactoryModel>()
+    override val localAssistedInjectFactories = mutableMapOf<AssistedInjectFactoryModel, AssistedInjectFactoryBinding>()
```
Comment (bacecek) [inline core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Using just `mutableSetOf<AssistedInjectFactoryBinding>()` is not enough since `AssistedInjectFactoryBinding` and `AssistedInjectFactoryModel` don't have `equals` methods and in that case `localAssistedInjectFactories` will have different instances of `AssistedInjectFactoryBinding` with the same `AssistedInjectFactoryModel`.

`Map` here is the easies and fastest way.

Comment (Jeffset) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Can you please explain why the `equals` method is of concern here? Binding instances generally do not have `equals`/`hashCode` because all their instances are managed via maps and should be unique, if expected. There should not be two different "local" binding instances for the same factory in the component, otherwise there would be a "conflicting binding" error. So it seems to me that we can just use `mutableSetOf<AssistedInjectFactoryBinding>()` here, can't we?

Comment (bacecek) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Sure, sorry — I should have described this in more detail.

AFAIK [here we have a code for reusing generated @AssistedFactory in subcomponents](https://github.com/yandex/yatagan/blob/c140c30171fd704f4d09ba35547580fa17f77d5c/core/graph/impl/src/main/kotlin/BindingGraphImpl.kt#L259). When using `Set<AssistedInjectFactoryBinding>()`, this code does nothing since parent and child components have a set of **different** `AssistedInjectFactoryBinding` that share **the same** `AssistedInjectFactoryModel`.
This case is reproduced in [CoreBindingsTest.basic assisted inject](https://github.com/yandex/yatagan/blob/f904ed46b677a7e60d6d3d85c779d4da8377890c/testing/tests/src/test/kotlin/CoreBindingsTest.kt#L794) test.

Because of that, we have two options:
- remove all `AssistedInjectFactoryBinding` that have the same `AssistedInjectFactoryModel` something like:
```kotlin
val localAssistedInjectFactoryModels = localAssistedInjectFactories.mapTo(hashSetOf()) { it.model }
val usesAssistedInjectFactories = child.localAssistedInjectFactories.removeAll { it.model in localAssistedInjectFactoryModels }
```
- use `Map<AssistedInjectFactoryModel, AssistedInjectFactoryBinding>` and remove keys in that case.

I have chosen the second option because it seems slightly more efficient in terms of performance.

Comment (Jeffset) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Thanks for the clarification! I was mildly surprised that parent and child components have different instances of bindings for the same factory. Ideally, this shouldn't be the case, and here's why.

So, alas, I remember now, that `AssistedInjectFactoryBinding` is implemented as an _implicit_ binding, just like regular `@Inject` constructor. Implicit bindings are materialized _in the current component first_, without checking if the matching binding is already present in the parent. This leads to potentially having multiple bindings for the same node in a parent and in a child (implicit bindings are never checked for conflicts, because we trust our own code that "implicitly" creates them). This behavior is indeed required for `@Inject` constructors to correctly deal with scopes. But for assisted inject bindings this makes no sense, because they do not have scopes and, on the contrary, actually reuse factories from the parent. So this "create in child, don't check the parent" thing is, in fact, a bit harmful/confusing for assisted inject bindings, as we see here.

So the **perfect solution** would be to change this behavior for assisted inject bindings. It might be slightly tricky, because such bindings are still _created_ implicitly (as in they don't have a physical method representing them in a module). So we would need to keep that part, but move their creation out of `materializeImplicit()` and into the `materializeLocal()` to change the order. Then we, as far as I see, don't need `localAssistedFactories` at all, as we could just do roughly `localBindings.filterIsInstance<AssistedInjectFactoryBinding>().filter { isNotNever }.map { it.model }`, and it would give us what we want. If you need more clarification here - please ask.

_If you are not open to make this change_, I'd advise you to use simply `Map<AssistedInjectFactoryModel, ConditionScope>` instead of `Map<AssistedInjectFactoryModel, AssistedInjectFactoryBinding>` here. Because clients (codegen) actually don't need the bindings, but only the condition scopes associated with the factories. I think it makes a bit more sense, doesn't expose unnecessary things, doesn't raise questions about binding equality like "why do we need factories as keys at all here".

**Review by Jeffset — CHANGES_REQUESTED** [review]

File: core/graph/impl/src/main/kotlin/BindingGraphImpl.kt (hunk 1 above)
Comment (bacecek) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Thank you for the clear explanation.

Unfortunately, I wasn’t able to implement the ideal solution because some `RuntimeTest` are failing.
If you don’t mind, I’d like to create a separate issue for the refactoring you mentioned.

**Review by Jeffset — APPROVED** [review]

File: core/graph/impl/src/main/kotlin/BindingGraphImpl.kt (hunk 1 above)
Comment (Jeffset) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: > Unfortunately, I wasn’t able to implement the ideal solution because some RuntimeTest are failing.
If you don’t mind, I’d like to create a separate issue for the refactoring you mentioned.

It's okay! You can create the issue if you see the need for in the future. I do not insist on this refactoring - it's purely internal.

Comment (Jeffset) [reply core/graph/impl/src/main/kotlin/BindingGraphImpl.kt]: Thank you for the changes
